baseurl = "https://primadonna.dev/"
title = "Primadonna 개발 블로그"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
  author = "Hyun Jinwoo"
  info = "Backend Developer"
  description = "primadonna's dev blog"
  keywords = "blog,developer,python,golang,fastapi,dotslashdash"
  avatarurl = "images/profile.jpg"

  favicon_32 = "images/favicon-32x32.png"
  favicon_16 = "images/favicon-16x16.png"

  since = 2022

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[params.utterances]
  repo = "PrimadonnaGit/primadonna-blog"
  issueTerm = "pathname"
  theme = "github-light"
  label = "comment"

[params.googleTagManager]
    id = "G-RYRBT21FK8"

[params.cloudflare]
    token = "fd4dccb654a349b387495925dbfd6242"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/PrimadonnaGit"

[[params.social]]
  name = "Facebook"
  icon = "fa fa-facebook fa-2x"
  weight = 2
  url = "https://www.facebook.com/profile.php?id=100079931731283"


[[menu.main]]
  name = "Categories"
  weight = 1
  url = "categories"
  target = "_blank"

[[menu.main]]
  name = "Posts"
  weight = 2
  url = "posts"
  target = "_blank"
